[package]
name = "tesseract-primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.53"
futures = "0.3.28"
ismp = { git = "https://github.com/polytope-labs/ismp-rs", branch = "main" }
pallet-ismp = { git = "https://github.com/polytope-labs/substrate-ismp", branch = "main" }
