[package]
name = "tesseract-primitives"
version = "0.1.0"
edition = "2021"
description = "Tesseract relayer primitives"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.53"
futures = "0.3.28"

serde = { version = "1.0.164", features = ["derive"] }
sp-core = { version = "21.0.0", default-features = false, features = ["serde"] }

ismp = { git = "https://github.com/polytope-labs/ismp-rs", branch = "main" }
pallet-ismp = { git = "https://github.com/polytope-labs/substrate-ismp", branch = "main" }
parity-scale-codec = "3.2.2"
