[package]
name = "tesseract"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs <hello@polytope.technology>"]

[workspace]
resolver = "2"

members = [
    "primitives",
    "consensus",
    "messaging",
    "parachain",
]
