[workspace]
resolver = "2"
members = [
    "primitives",
    "consensus",
    "messaging",
    "substrate/common",
    "substrate/parachain",
    "relayer",
    "integration-tests",
]

[profile.release]
panic = "unwind"
opt-level = 3
