[package]
name = "tesseract-message"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
log = "0.4.17"
futures = "0.3.28"
tokio = { version = "1.27.0", features = ["full"] }
pallet-ismp = { git = "ssh://git@github.com/polytope-labs/substrate-ismp.git", branch = "main" }
tesseract-primitives = { path = "../primitives" }
ismp = { git = "ssh://git@github.com/polytope-labs/ismp-rs.git", branch = "main" }

